- hosts: agents_private
  remote_user: centos
  become: yes
  tasks:

    - shell: systemctl kill -s SIGUSR1 dcos-mesos-slave && systemctl stop dcos-mesos-slave
      ignore_errors: true

    - name: remove old mesos-resources file
      file: path=/var/lib/dcos/mesos-resources state=absent
      ignore_errors: true

    - name: remove mesos state
      file: path=/var/lib/mesos/slave/meta/slaves/latest state=absent
      ignore_errors: true

    - name: create mount point
      file: path=/dcos/volume0 state=directory mode=0777

    - shell: dd if=/dev/zero of=/root/volume0.img bs=1M count=2000
      ignore_errors: true

    - shell: losetup /dev/loop0 /root/volume0.img
      ignore_errors: true

    - shell: mkfs -t ext4 /dev/loop0
      ignore_errors: true

    - shell: losetup -d /dev/loop0
      ignore_errors: true

    - shell: sudo sh -c 'echo "/root/volume0.img /dcos/volume0 auto loop 0 2" | tee -a /etc/fstab'

    - shell: mount /dcos/volume0
      ignore_errors: true

    - name: reboot
      reboot: