- name: install nvidia drivers
  hosts: agents
  become: true

  vars:
    cuda_download: http://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-repo-rhel7-9.1.85-1.x86_64.rpm

  tasks:

    - name: update all packages
      yum:
        name: "*"
        state: latest
        exclude: docker-engine

    - name: make sure epel-release is installed
      yum:
        name: epel-release
        state: present

    - name: install required system packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - kernel-devel
        - kernel-headers
        - gcc
        - make
        - dkms

    - name: download cuda repo file
      get_url: url="{{ cuda_download }}" dest=/tmp/cuda-repo.rpm mode=0440 force=yes

    - name: install cuda repo rpm from a local file
      yum:
        name: /tmp/cuda-repo.rpm
        state: present

    - name: install cuda
      yum:
        name: cuda
        update_cache: yes
        state: latest

    - name: install nvidia-persistenced systemd service
      template:
        src: nvidia-persistenced.service.j2
        dest: /etc/systemd/system/nvidia-persistenced.service

    - name: enable nvidia-persistenced systemd service
      systemd:
        name: nvidia-persistenced.service
        enabled: yes

    - name: reboot
      shell: sleep 2 && /sbin/shutdown -r now "ansible triggered"
      async: 1
      poll: 0
      ignore_errors: true

    - name: wait for the server to reboot
      local_action: wait_for host="{{ansible_host}}" state=started delay=30 timeout=300
      become: false

    - name: test nvidia driver
      shell: nvidia-smi
