
- hosts: masters
  remote_user: centos
  become: true

  tasks:

  - name: configure telegraf for mesos masters
    blockinfile:
      dest: "/var/lib/dcos/telegraf/telegraf.d/mesos-master.conf"
      state: present
      create: yes
      block: |
        # Gathers all Mesos metrics
        [[inputs.mesos]]
          # The interval at which to collect metrics
          interval = "60s"
          # Timeout, in ms.
          timeout = 30000
          # A list of Mesos masters.
          masters = ["http://$DCOS_NODE_PRIVATE_IP:5050"]

  - name: restart dcos-telegraf.service for mesos masters
    systemd:
      name: dcos-telegraf.service
      state: restarted
      enabled: yes

- hosts: agents,agent_publics
  remote_user: centos
  become: true

  tasks:

  - name: configure telegraf for mesos agents
    blockinfile:
      dest: "/var/lib/dcos/telegraf/telegraf.d/mesos-agent.conf"
      state: present
      create: yes
      block: |
        # Gathers all Mesos metrics
        [[inputs.mesos]]
          # The interval at which to collect metrics
          interval = "60s"
          # Timeout, in ms.
          timeout = 30000
          # A list of Mesos slaves.
          slaves = ["http://$DCOS_NODE_PRIVATE_IP:5051"]

  - name: restart dcos-telegraf.service for mesos agents
    systemd:
      name: dcos-telegraf.service
      state: restarted
      enabled: yes